name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages
          npm run deploy

      - name: Deploy to server
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TONCOIN_WALLET_ADDRESS: ${{ secrets.TONCOIN_WALLET_ADDRESS }}
          TON_WEBHOOK_SECRET: ${{ secrets.TON_WEBHOOK_SECRET }}
        run: |
          echo "Deploying to server..."
          npm start
